/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amrish' at '5/25/16 6:56 PM' with Gradle 2.12
 *
 * @author amrish, @date 5/25/16 6:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
